---
title: "publishexample"
author: "Margaux"
date: "02/12/2020"
output:
  html_document:
    theme: yeti
    smart: true
    highlight: textmate
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



# Title
## Second sub title
### Third sub title

```{r cars}
library(tidyverse)
library(tmap)
library(geojsonio)
library(plotly)
library(rgdal)
library(mapview)
library(sf)
library(sp)
library(car)
library(fs)
library(janitor)
library(dplyr)
library(data.table)
library(spdep)
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(geojson)
library(tmaptools)
library(ggplot2)
library(spatialreg)
library(broom)
library(br)
library(spgwr)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggpubr)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
